package com.thekoldar.aoe_rms_spoon.models;

/**
 * Class identifiying a version of Age fo Empires.
 * 
 * It actys as a factory class for building nodes. Each AST node depends on the age of empires you are considering
 * 
 * @author massi
 *
 */

//TROOT,TPLAYER_SETUP,TLAND_GENERATION,TELEVATION_GENERATION,TCLIFF_GENERATION,TTERRAIN_GENERATION,TCONNECTION_GENERATION,TOBJECTS_GENERATION,
//TCREATE_PLAYER_LANDS,TRANDOM_PLACEMENT,TGROUPED_BY_TEAM,TDIRECT_PLACEMENT,TNOMAD_RESOURCES,TAI_INFO_MAP_TYPE,TWEATHER_TYPE,TEFFECT_AMOUNT,TEFFECT_PERCENT,TGUARD_STATE,TTERRAIN_STATE,TSET_GAIA_CIVILIZATION,TBEHAVIOR_VERSION,TBASE_TERRAIN,TBASE_LAYER,TENABLE_WAVES,TCREATE_LAND,TTERRAIN_TYPE,TLAND_PERCENT,TNUMBER_OF_TILES,TBASE_SIZE,TLAND_POSITION,TCIRCLE_RADIUS,TLEFT_BORDER,TRIGHT_BORDER,TTOP_BORDER,TBOTTOM_BORDER,TBORDER_FUZZINESS,TCLUMPING_FACTOR,TBASE_ELEVATION,TASSIGN_TO_PLAYER,TASSIGN_TO,TZONE,TSET_ZONE_BY_TEAM,TSET_ZONE_RANDOMLY,TOTHER_ZONE_AVOIDANCE_DISTANCE,TMIN_PLACEMENT_DISTANCE,TLAND_ID,TCREATE_ELEVATION,TNUMBER_OF_CLUMPS,TSET_SCALE_BY_SIZE,TSET_SCALE_BY_GROUPS,TSPACING,TENABLE_BALANCED_ELEVATION,TMIN_NUMBER_OF_CLIFFS,TMAX_NUMBER_OF_CLIFFS,TMIN_LENGTH_OF_CLIFF,TMAX_LENGTH_OF_CLIFF,TCLIFF_CURLINESS,TMIN_DISTANCE_CLIFFS,TMIN_TERRAIN_DISTANCE,TCOLOR_CORRECTION,TCREATE_TERRAIN,TTERRAIN_MASK,TSPACING_TO_OTHER_TERRAIN_TYPES,TSET_FLAT_TERRAIN_ONLY,TSET_AVOID_PLAYER_START_AREAS,THEIGHT_LIMITS,TCREATE_CONNECT_ALL_PLAYERS_LAND,TCREATE_CONNECT_TEAMS_LANDS,TCREATE_CONNECT_ALL_LANDS,TCREATE_CONNECT_SAME_LAND_ZONES,TCREATE_CONNECT_TO_NONPLAYER_LAND,TDEFAULT_TERRAIN_REPLACEMENT,TREPLACE_TERRAIN,TTERRAIN_COST,TTERRAIN_SIZE,TCREATE_OBJECT,TNUMBER_OF_OBJECTS,TNUMBER_OF_GROUPS,TGROUP_VARIANCE,TRESOURCE_DELTA,TSECOND_OBJECT,TSET_SCALING_TO_MAP_SIZE,TSET_SCALING_TO_PLAYER_NUMBER,TSET_PLACE_FOR_EVERY_PLAYER,TPLACE_ON_SPECIFIC_LAND_ID,TSET_GAIA_OBJECT_ONLY,TSET_GAIA_UNCONVERTIBLE,TGROUP_PLACEMENT_RADIUS,TSET_TIGHT_GROUPING,TSET_LOOSE_GROUPING,TTERRAIN_TO_PLACE_ON,TLAYER_TO_PLACE_ON,TPLACE_ON_FOREST_ZONE,TAVOID_FOREST_ZONE,TAVOID_CLIFF_ZONE,TMIN_DISTANCE_TO_PLAYERS,TMAX_DISTANCE_TO_PLAYERS,TMAX_DISTANCE_TO_OTHER_ZONES,TMIN_DISTANCE_GROUP_PLACEMENT,TTEMP_MIN_DISTANCE_GROUP_PLACEMENT,TFIND_CLOSEST,TFORCE_PLACEMENT,TACTOR_AREA,TACTOR_AREA_RADIUS,TACTOR_AREA_TO_PLACE_IN,TAVOID_ACTOR_AREA,TAVOID_ALL_ACTOR_AREAS,
//TCOMMENT,TINCLUDE,TINCLUDE_DRS,TCONST,TDEFINE

//<
//ROOT,
//
//TPLAYER_SETUP,
//TLAND_GENERATION,
//TELEVATION_GENERATION,
//TCLIFF_GENERATION,
//TTERRAIN_GENERATION,
//TCONNECTION_GENERATION,
//TOBJECTS_GENERATION,
//
//TCREATE_PLAYER_LANDS,
//TRANDOM_PLACEMENT,
//TGROUPED_BY_TEAM,
//TDIRECT_PLACEMENT,
//TNOMAD_RESOURCES,
//TAI_INFO_MAP_TYPE,
//TWEATHER_TYPE,
//TEFFECT_AMOUNT,
//TEFFECT_PERCENT,
//TGUARD_STATE,
//TTERRAIN_STATE,
//TSET_GAIA_CIVILIZATION,
//TBEHAVIOR_VERSION,
//TBASE_TERRAIN,
//TBASE_LAYER,
//TENABLE_WAVES,
//TCREATE_LAND,
//TTERRAIN_TYPE,
//TLAND_PERCENT,
//TNUMBER_OF_TILES,
//TBASE_SIZE,
//TLAND_POSITION,
//TCIRCLE_RADIUS,
//TLEFT_BORDER,
//TRIGHT_BORDER,
//TTOP_BORDER,
//TBOTTOM_BORDER,
//TBORDER_FUZZINESS,
//TCLUMPING_FACTOR,
//TBASE_ELEVATION,
//TASSIGN_TO_PLAYER,
//TASSIGN_TO,
//TZONE,
//TSET_ZONE_BY_TEAM,
//TSET_ZONE_RANDOMLY,
//TOTHER_ZONE_AVOIDANCE_DISTANCE,
//TMIN_PLACEMENT_DISTANCE,
//TLAND_ID,
//TCREATE_ELEVATION,
//TNUMBER_OF_CLUMPS,
//TSET_SCALE_BY_SIZE,
//TSET_SCALE_BY_GROUPS,
//TSPACING,
//TENABLE_BALANCED_ELEVATION,
//TMIN_NUMBER_OF_CLIFFS,
//TMAX_NUMBER_OF_CLIFFS,
//TMIN_LENGTH_OF_CLIFF,
//TMAX_LENGTH_OF_CLIFF,
//TCLIFF_CURLINESS,
//TMIN_DISTANCE_CLIFFS,
//TMIN_TERRAIN_DISTANCE,
//TCOLOR_CORRECTION,
//TCREATE_TERRAIN,
//TTERRAIN_MASK,
//TSPACING_TO_OTHER_TERRAIN_TYPES,
//TSET_FLAT_TERRAIN_ONLY,
//TSET_AVOID_PLAYER_START_AREAS,
//THEIGHT_LIMITS,
//TCREATE_CONNECT_ALL_PLAYERS_LAND,
//TCREATE_CONNECT_TEAMS_LANDS,
//TCREATE_CONNECT_ALL_LANDS,
//TCREATE_CONNECT_SAME_LAND_ZONES,
//TCREATE_CONNECT_TO_NONPLAYER_LAND,
//TDEFAULT_TERRAIN_REPLACEMENT,
//TREPLACE_TERRAIN,
//TTERRAIN_COST,
//TTERRAIN_SIZE,
//TCREATE_OBJECT,
//TNUMBER_OF_OBJECTS,
//TNUMBER_OF_GROUPS,
//TGROUP_VARIANCE,
//TRESOURCE_DELTA,
//TSECOND_OBJECT,
//TSET_SCALING_TO_MAP_SIZE,
//TSET_SCALING_TO_PLAYER_NUMBER,
//TSET_PLACE_FOR_EVERY_PLAYER,
//TPLACE_ON_SPECIFIC_LAND_ID,
//TSET_GAIA_OBJECT_ONLY,
//TSET_GAIA_UNCONVERTIBLE,
//TGROUP_PLACEMENT_RADIUS,
//TSET_TIGHT_GROUPING,
//TSET_LOOSE_GROUPING,
//TTERRAIN_TO_PLACE_ON,
//TLAYER_TO_PLACE_ON,
//TPLACE_ON_FOREST_ZONE,
//TAVOID_FOREST_ZONE,
//TAVOID_CLIFF_ZONE,
//TMIN_DISTANCE_TO_PLAYERS,
//TMAX_DISTANCE_TO_PLAYERS,
//TMAX_DISTANCE_TO_OTHER_ZONES,
//TMIN_DISTANCE_GROUP_PLACEMENT,
//TTEMP_MIN_DISTANCE_GROUP_PLACEMENT,
//TFIND_CLOSEST,
//TFORCE_PLACEMENT,
//TACTOR_AREA,
//TACTOR_AREA_RADIUS,
//TACTOR_AREA_TO_PLACE_IN,
//TAVOID_ACTOR_AREA,
//TAVOID_ALL_ACTOR_AREAS,
//
//TCOMMENT,
//TINCLUDE,
//TINCLUDE_DRS,
//TCONST,
//TDEFINE
//>

public abstract class AbstractAoEVersion<TROOT,TPLAYER_SETUP,TLAND_GENERATION,TELEVATION_GENERATION,TCLIFF_GENERATION,TTERRAIN_GENERATION,TCONNECTION_GENERATION,TOBJECTS_GENERATION,TCREATE_PLAYER_LANDS,TRANDOM_PLACEMENT,TGROUPED_BY_TEAM,TDIRECT_PLACEMENT,TNOMAD_RESOURCES,TAI_INFO_MAP_TYPE,TWEATHER_TYPE,TEFFECT_AMOUNT,TEFFECT_PERCENT,TGUARD_STATE,TTERRAIN_STATE,TSET_GAIA_CIVILIZATION,TBEHAVIOR_VERSION,TBASE_TERRAIN,TBASE_LAYER,TENABLE_WAVES,TCREATE_LAND,TTERRAIN_TYPE,TLAND_PERCENT,TNUMBER_OF_TILES,TBASE_SIZE,TLAND_POSITION,TCIRCLE_RADIUS,TLEFT_BORDER,TRIGHT_BORDER,TTOP_BORDER,TBOTTOM_BORDER,TBORDER_FUZZINESS,TCLUMPING_FACTOR,TBASE_ELEVATION,TASSIGN_TO_PLAYER,TASSIGN_TO,TZONE,TSET_ZONE_BY_TEAM,TSET_ZONE_RANDOMLY,TOTHER_ZONE_AVOIDANCE_DISTANCE,TMIN_PLACEMENT_DISTANCE,TLAND_ID,TCREATE_ELEVATION,TNUMBER_OF_CLUMPS,TSET_SCALE_BY_SIZE,TSET_SCALE_BY_GROUPS,TSPACING,TENABLE_BALANCED_ELEVATION,TMIN_NUMBER_OF_CLIFFS,TMAX_NUMBER_OF_CLIFFS,TMIN_LENGTH_OF_CLIFF,TMAX_LENGTH_OF_CLIFF,TCLIFF_CURLINESS,TMIN_DISTANCE_CLIFFS,TMIN_TERRAIN_DISTANCE,TCOLOR_CORRECTION,TCREATE_TERRAIN,TTERRAIN_MASK,TSPACING_TO_OTHER_TERRAIN_TYPES,TSET_FLAT_TERRAIN_ONLY,TSET_AVOID_PLAYER_START_AREAS,THEIGHT_LIMITS,TCREATE_CONNECT_ALL_PLAYERS_LAND,TCREATE_CONNECT_TEAMS_LANDS,TCREATE_CONNECT_ALL_LANDS,TCREATE_CONNECT_SAME_LAND_ZONES,TCREATE_CONNECT_TO_NONPLAYER_LAND,TDEFAULT_TERRAIN_REPLACEMENT,TREPLACE_TERRAIN,TTERRAIN_COST,TTERRAIN_SIZE,TCREATE_OBJECT,TNUMBER_OF_OBJECTS,TNUMBER_OF_GROUPS,TGROUP_VARIANCE,TRESOURCE_DELTA,TSECOND_OBJECT,TSET_SCALING_TO_MAP_SIZE,TSET_SCALING_TO_PLAYER_NUMBER,TSET_PLACE_FOR_EVERY_PLAYER,TPLACE_ON_SPECIFIC_LAND_ID,TSET_GAIA_OBJECT_ONLY,TSET_GAIA_UNCONVERTIBLE,TGROUP_PLACEMENT_RADIUS,TSET_TIGHT_GROUPING,TSET_LOOSE_GROUPING,TTERRAIN_TO_PLACE_ON,TLAYER_TO_PLACE_ON,TPLACE_ON_FOREST_ZONE,TAVOID_FOREST_ZONE,TAVOID_CLIFF_ZONE,TMIN_DISTANCE_TO_PLAYERS,TMAX_DISTANCE_TO_PLAYERS,TMAX_DISTANCE_TO_OTHER_ZONES,TMIN_DISTANCE_GROUP_PLACEMENT,TTEMP_MIN_DISTANCE_GROUP_PLACEMENT,TFIND_CLOSEST,TFORCE_PLACEMENT,TACTOR_AREA,TACTOR_AREA_RADIUS,TACTOR_AREA_TO_PLACE_IN,TAVOID_ACTOR_AREA,TAVOID_ALL_ACTOR_AREAS,TCOMMENT,TINCLUDE,TINCLUDE_DRS,TCONST,TDEFINE> {
	
	public abstract TPLAYER_SETUP player_setup();
	public abstract TLAND_GENERATION land_generation();
	public abstract TELEVATION_GENERATION elevation_generation();
	public abstract TCLIFF_GENERATION cliff_generation();
	public abstract TTERRAIN_GENERATION terrain_generation();
	public abstract TCONNECTION_GENERATION connection_generation();
	public abstract TOBJECTS_GENERATION objects_generation();

	public abstract TCREATE_PLAYER_LANDS create_player_plands();
	public abstract TRANDOM_PLACEMENT random_placement();
	public abstract TGROUPED_BY_TEAM grouped_by_team();
	public abstract TDIRECT_PLACEMENT DIRECT_PLACEMENT();
	public abstract TNOMAD_RESOURCES NOMAD_RESOURCES();
	public abstract TAI_INFO_MAP_TYPE AI_INFO_MAP_TYPE();
	public abstract TWEATHER_TYPE WEATHER_TYPE();
	public abstract TEFFECT_AMOUNT EFFECT_AMOUNT();
	public abstract TEFFECT_PERCENT EFFECT_PERCENT();
	public abstract TGUARD_STATE GUARD_STATE();
	public abstract TTERRAIN_STATE TERRAIN_STATE();
	public abstract TSET_GAIA_CIVILIZATION SET_GAIA_CIVILIZATION();
	public abstract TBEHAVIOR_VERSION BEHAVIOR_VERSION();
	public abstract TBASE_TERRAIN BASE_TERRAIN();
	public abstract TBASE_LAYER BASE_LAYER();
	public abstract TENABLE_WAVES ENABLE_WAVES();
	public abstract TCREATE_LAND CREATE_LAND();
	public abstract TTERRAIN_TYPE TERRAIN_TYPE();
	public abstract TLAND_PERCENT LAND_PERCENT();
	public abstract TNUMBER_OF_TILES NUMBER_OF_TILES();
	public abstract TBASE_SIZE BASE_SIZE();
	public abstract TLAND_POSITION LAND_POSITION();
	public abstract TCIRCLE_RADIUS CIRCLE_RADIUS();
	public abstract TLEFT_BORDER LEFT_BORDER();
	public abstract TRIGHT_BORDER RIGHT_BORDER();
	public abstract TTOP_BORDER TOP_BORDER();
	public abstract TBOTTOM_BORDER BOTTOM_BORDER();
	public abstract TBORDER_FUZZINESS BORDER_FUZZINESS();
	public abstract TCLUMPING_FACTOR CLUMPING_FACTOR();
	public abstract TBASE_ELEVATION BASE_ELEVATION();
	public abstract TASSIGN_TO_PLAYER ASSIGN_TO_PLAYER();
	public abstract TASSIGN_TO ASSIGN_TO();
	public abstract TZONE ZONE();
	public abstract TSET_ZONE_BY_TEAM SET_ZONE_BY_TEAM();
	public abstract TSET_ZONE_RANDOMLY SET_ZONE_RANDOMLY();
	public abstract TOTHER_ZONE_AVOIDANCE_DISTANCE OTHER_ZONE_AVOIDANCE_DISTANCE();
	public abstract TMIN_PLACEMENT_DISTANCE MIN_PLACEMENT_DISTANCE();
	public abstract TLAND_ID LAND_ID();
	public abstract TCREATE_ELEVATION CREATE_ELEVATION();
	public abstract TNUMBER_OF_CLUMPS NUMBER_OF_CLUMPS();
	public abstract TSET_SCALE_BY_SIZE SET_SCALE_BY_SIZE();
	public abstract TSET_SCALE_BY_GROUPS SET_SCALE_BY_GROUPS();
	public abstract TSPACING SPACING();
	public abstract TENABLE_BALANCED_ELEVATION ENABLE_BALANCED_ELEVATION();
	public abstract TMIN_NUMBER_OF_CLIFFS MIN_NUMBER_OF_CLIFFS();
	public abstract TMAX_NUMBER_OF_CLIFFS MAX_NUMBER_OF_CLIFFS();
	public abstract TMIN_LENGTH_OF_CLIFF MIN_LENGTH_OF_CLIFF();
	public abstract TMAX_LENGTH_OF_CLIFF MAX_LENGTH_OF_CLIFF();
	public abstract TCLIFF_CURLINESS CLIFF_CURLINESS();
	public abstract TMIN_DISTANCE_CLIFFS MIN_DISTANCE_CLIFFS();
	public abstract TMIN_TERRAIN_DISTANCE MIN_TERRAIN_DISTANCE();
	public abstract TCOLOR_CORRECTION COLOR_CORRECTION();
	public abstract TCREATE_TERRAIN CREATE_TERRAIN();
	public abstract TTERRAIN_MASK TERRAIN_MASK();
	public abstract TSPACING_TO_OTHER_TERRAIN_TYPES SPACING_TO_OTHER_TERRAIN_TYPES();
	public abstract TSET_FLAT_TERRAIN_ONLY SET_FLAT_TERRAIN_ONLY();
	public abstract TSET_AVOID_PLAYER_START_AREAS SET_AVOID_PLAYER_START_AREAS();
	public abstract THEIGHT_LIMITS HEIGHT_LIMITS();
	public abstract TCREATE_CONNECT_ALL_PLAYERS_LAND CREATE_CONNECT_ALL_PLAYERS_LAND();
	public abstract TCREATE_CONNECT_TEAMS_LANDS CREATE_CONNECT_TEAMS_LANDS();
	public abstract TCREATE_CONNECT_ALL_LANDS CREATE_CONNECT_ALL_LANDS();
	public abstract TCREATE_CONNECT_SAME_LAND_ZONES CREATE_CONNECT_SAME_LAND_ZONES();
	public abstract TCREATE_CONNECT_TO_NONPLAYER_LAND CREATE_CONNECT_TO_NONPLAYER_LAND();
	public abstract TDEFAULT_TERRAIN_REPLACEMENT DEFAULT_TERRAIN_REPLACEMENT();
	public abstract TREPLACE_TERRAIN REPLACE_TERRAIN();
	public abstract TTERRAIN_COST TERRAIN_COST();
	public abstract TTERRAIN_SIZE TERRAIN_SIZE();
	public abstract TCREATE_OBJECT CREATE_OBJECT();
	public abstract TNUMBER_OF_OBJECTS NUMBER_OF_OBJECTS();
	public abstract TNUMBER_OF_GROUPS NUMBER_OF_GROUPS();
	public abstract TGROUP_VARIANCE GROUP_VARIANCE();
	public abstract TRESOURCE_DELTA RESOURCE_DELTA();
	public abstract TSECOND_OBJECT SECOND_OBJECT();
	public abstract TSET_SCALING_TO_MAP_SIZE SET_SCALING_TO_MAP_SIZE();
	public abstract TSET_SCALING_TO_PLAYER_NUMBER SET_SCALING_TO_PLAYER_NUMBER();
	public abstract TSET_PLACE_FOR_EVERY_PLAYER SET_PLACE_FOR_EVERY_PLAYER();
	public abstract TPLACE_ON_SPECIFIC_LAND_ID PLACE_ON_SPECIFIC_LAND_ID();
	public abstract TSET_GAIA_OBJECT_ONLY SET_GAIA_OBJECT_ONLY();
	public abstract TSET_GAIA_UNCONVERTIBLE SET_GAIA_UNCONVERTIBLE();
	public abstract TGROUP_PLACEMENT_RADIUS GROUP_PLACEMENT_RADIUS();
	public abstract TSET_TIGHT_GROUPING SET_TIGHT_GROUPING();
	public abstract TSET_LOOSE_GROUPING SET_LOOSE_GROUPING();
	public abstract TTERRAIN_TO_PLACE_ON TERRAIN_TO_PLACE_ON();
	public abstract TLAYER_TO_PLACE_ON LAYER_TO_PLACE_ON();
	public abstract TPLACE_ON_FOREST_ZONE PLACE_ON_FOREST_ZONE();
	public abstract TAVOID_FOREST_ZONE AVOID_FOREST_ZONE();
	public abstract TAVOID_CLIFF_ZONE AVOID_CLIFF_ZONE();
	public abstract TMIN_DISTANCE_TO_PLAYERS MIN_DISTANCE_TO_PLAYERS();
	public abstract TMAX_DISTANCE_TO_PLAYERS MAX_DISTANCE_TO_PLAYERS();
	public abstract TMAX_DISTANCE_TO_OTHER_ZONES MAX_DISTANCE_TO_OTHER_ZONES();
	public abstract TMIN_DISTANCE_GROUP_PLACEMENT MIN_DISTANCE_GROUP_PLACEMENT();
	public abstract TTEMP_MIN_DISTANCE_GROUP_PLACEMENT TEMP_MIN_DISTANCE_GROUP_PLACEMENT();
	public abstract TFIND_CLOSEST FIND_CLOSEST();
	public abstract TFORCE_PLACEMENT FORCE_PLACEMENT();
	public abstract TACTOR_AREA ACTOR_AREA();
	public abstract TACTOR_AREA_RADIUS ACTOR_AREA_RADIUS();
	public abstract TACTOR_AREA_TO_PLACE_IN ACTOR_AREA_TO_PLACE_IN();
	public abstract TAVOID_ACTOR_AREA AVOID_ACTOR_AREA();
	public abstract TAVOID_ALL_ACTOR_AREAS AVOID_ALL_ACTOR_AREAS();

	public abstract TCOMMENT COMMENT();
	public abstract TINCLUDE INCLUDE();
	public abstract TINCLUDE_DRS INCLUDE_DRS();
	public abstract TCONST CONST();
	public abstract TDEFINE DEFINE(); 
	
}
